### ISSUE TITLE
Create IconUtils Test

### ISSUE THREAD

**Issue by robnn** [javas-csavok/outlay#6]

**Comment by stahopeti** [comment]
Created unit tests for getAll and loadCategoryIcon methods. 

I couldn't make for the getXYZIcon methods, because In the IconicsDrawable I get an exception in the prepare function for the mPaint.setStyle(....) because it is not mocked. I don't know how to make it happen

https://github.com/javas-csavok/outlay/commit/c66b5c6a5c5c126729c830adef0ba1f48e94ef95

**Comment by robnn** [comment]
Nice job

**Comment by stahopeti** [comment]
Implemented more tests

https://github.com/javas-csavok/outlay/commit/ae820d318da99b218c657b593a71e2c505eb9cf1

**Comment by robnn** [comment]
👍
